services:

  db:
    image: postgres
    container_name: agro_postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ../db/dados_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agrospray
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agro_user -d agro_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  # backend:
  #   image: backend
  #   container_name: backend
  #   ports:
  #     - "30000:30000"
  #   restart: unless-stopped
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   entrypoint: ["sh", "-c", "sleep 5 && ./main"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

